# Permalinks
permalink:           pretty

# Setup
title:               Jinkyung
tagline:             I have something to say...
url:                 http://jinkyung.github.io
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Jinkyung
  url:               http://jinkyung.github.io
  email:             jinkyungj@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/jinkyung/jinkyung.github.io

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
